"""add access_level to employees

Revision ID: 59e79e7ed8d1
Revises: bf0186243f59
Create Date: 2026-10-01 16:48:07.568614

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "59e79e7ed8d1"
down_revision: Union[str, Sequence[str], None] = "bf0186243f59"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default is required here (unlike documents' original
    # creation migration, which started from an empty table): the
    # employees table already has rows from scripts/seed_demo_data.py,
    # and a NOT NULL column with no default fails against them. Matches
    # the ORM-side default (AccessLevel.INTERNAL) so existing employees
    # behave the same as new ones.
    op.add_column(
        "employees",
        sa.Column("access_level", sa.String(length=16), nullable=False, server_default="internal"),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("employees", "access_level")
    # ### end Alembic commands ###
